DEEPSORT:
  REID_CKPT: "model/tracker/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.45
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 70
  MAX_AGE: 10
  N_INIT: 3
  NN_BUDGET: 100
  
